DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS AUTHORITIES;
DROP INDEX IF EXISTS IX_AUTH_USERNAME;

CREATE TABLE IF NOT EXISTS USERS(
    USERNAME VARCHAR2(50) NOT NULL PRIMARY KEY,
	PASSWORD VARCHAR2(50) NOT NULL,
	ENABLED CHAR(1) DEFAULT '1');

CREATE TABLE IF NOT EXISTS AUTHORITIES (
    USERNAME VARCHAR2(50) NOT NULL,
	AUTHORITY VARCHAR2(50) NOT NULL,
	CONSTRAINT FK_AUTHORITIES_USERS
	FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME));

CREATE UNIQUE INDEX IX_AUTH_USERNAME 
    ON AUTHORITIES (USERNAME, AUTHORITY);